RxSwiftCommunity/rxswiftcommunity.github.io

- Gemfile
- Gemfile.lock
- README.md
- Rakefile
And some documentation for how to contribute.
> Adds deploys

- .travis.yml
- Rakefile
Now it can deploy from the `source` branch instead of someone having to do it by hand.
> Automates deploys

- README.md
- Rakefile
> Updated autodeploys

- Rakefile
> Fixes deploys.

- source/CNAME
> Add CNAME file to point to community.rxswift.org

- README.md
Also add branch specification for PR's
> Change README header to url community.rxswift.org

- README.md
> Update README logo src to absolute url

- source/index.html.erb
When I changed from 12-wide to 10-wide, I forgot to add a 1-offset to centre the content :sweat_smile:
> Re-centres content.

- data/items.yml
Added [SugarRecord](https://github.com/swiftreactive/sugarrecord) to the list :)
> Added Realm to the list of projects using RxSwift

- data/items.yml
Added ReactiveCommander to the list. A library I recently implemented that helps to implement the Command Pattern using `NSOperation`s and `NSOperationQueue`s and exposing reactive components to subscribe to execution events.
> Added ReactiveCommander Library

- data/items.yml
> Adds RxNimble

- data/items.yml
@ashfurrow is this the right spot on the page to add RxGesture?
> adds RxGesture

- data/items.yml
Closes RxSwiftCommunity/contributors#12
Hey @ashfurrow, I've finished renaming NKMultipeer -> RxMultipeer.
I seem to have lost edit description priviliges on https://github.com/RxSwiftCommunity/RxMultipeer though, so if you can give it a suitable description for me that'd be great ;)
> Add RxMultipeer

- data/items.yml
I was pushed origin remote by mistake. I'm sorry for my mistake. 😢
> Add GoogleMaps

- data/items.yml
Hello, RxGRDB now lives in RxSwiftCommunity!
> Add RxGRDB

- Gemfile.lock
- data/items.yml
This PR merges #55 into the source branch. CI was failing there due to a problem with the JSON gem, so I updated it (things worked fine locally). Hoping this fixes things.
> Merges #55.

- data/items.yml
adds RxRealmDataSources to the list of rx libs
> Adds RxRealmDataSources

- data/items.yml
adds two more libs to the list
> adds rxfeedback and rxanimated

- data/items.yml
This commit adds the project RxFlow which is an implementation of the Coordinator pattern in a Reactive way with RxSwift.
> add RxFlow

- data/items.yml
Add RxASDataSources: **RxDataSources** for AsyncDisplayKit
> Add RxASDataSources

- data/items.yml
Title pretty much explains everything that was done.
> Added RxDatasources, moved RxFacebook to extension's section

- data/items.yml
Hi.
I've just uploaded this small project I developed to teach myself Reactive programming and RxSwift. I want to make it visible in order to receive feedback to improve :)
Thank you.
> Adds RxBookshelf to the projects section

- Gemfile
- Gemfile.lock
This specifically updates `ffi` and `sprockets` to resolve a security vulnerability in both of these. I tried updating everything in #84 but that caused issues so I only cherry-picked the dependencies with issue.
> Update ffi, sprockets and middleman vulnerabilities

- data/items.yml
https://github.com/RxSwiftCommunity/contributors/issues/54
> add RxCocoa-Texture

- data/items.yml
Add [RxNuke](https://github.com/kean/RxNuke)
> Add RxNuke

- data/items.yml
> Add RxBinding.

- data/items.yml
Add [GiTiny](https://github.com/k-lpmg/GiTiny)
> Add GiTiny

- data/items.yml
> Add RxAlert

- data/items.yml
> add RxIGListKit

- data/items.yml
Added RxEnumKit.
This will allow this kind of pattern with Observables and SharedSequences
```
enum MyEvent: CaseAccessible {
case eventA(String)
case eventB(foo: Int)
}
let observable: Observable<MyEvent>
observable.capture(case: MyEvent.eventA)
.subscribe(onNext: { value in //String
...
})
observable.map(case: MyEvent.eventB, String.init)
.subscribe(onNext: { value in // String
...
})
```
Operators included in RxEnumKit:
- `filter(case: )`
- `exclude(case: )`
- `capture(case: )`
- `map(case: )`
- `compactMap(case:)`
- `flatMap(case:)`
- `flatMapFirst(case:)`
- `flatMapLatest(case:)`
> Add RxEnumKit

- data/items.yml
A reactive wrapper built around Yalantis/Koloda
> Add RxKoloda

- data/items.yml
This project using RxSwift, MVVM-C and https://jsonplaceholder.typicode.com/ for dummy json response
> RxTodo-app added

- data/items.yml
[GitTime](https://github.com/87kangsw/GitTime) is an iOS app that allows you to explore GitHub activities and trends.
This project is implemented with [Reactorkit](https://github.com/ReactorKit/ReactorKit) architecture and RxSwift.
> Add GitTime

- data/items.yml
[reactorkit-keyboard-example](https://github.com/techinpark/reactorkit-keyboard-example) iOS Application example for develop keyboard-extensions ⌨️
This project is implemented with [Reactorkit](https://github.com/ReactorKit/ReactorKit) architecture and RxSwift.
> Add reactorkit-keyboard-example

- data/items.yml
This project allows developers to obtain information about the battery in a reactive manner.
> RxBatteryManager added

- data/items.yml
[Spaklers](https://github.com/dev-jason-hwkim/Sparklers) example is an iOS app that make spaklers photo.
This project is implemented with [Reactorkit](https://github.com/ReactorKit/ReactorKit) architecture and RxSwift.
> Add Spaklers
